// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiCKs2FMlestAHMgT-l3YujLJ59xS66oE',
    appId: '1:132147122480:web:c6983a2297289b355278f5',
    messagingSenderId: '132147122480',
    projectId: 'austhivenet1',
    authDomain: 'austhivenet1.firebaseapp.com',
    storageBucket: 'austhivenet1.appspot.com',
    measurementId: 'G-PCD07FVNLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOrClcaTEmyA-8wZHcQ0vpTDQHo6qjM4I',
    appId: '1:132147122480:android:947118bccbf87d895278f5',
    messagingSenderId: '132147122480',
    projectId: 'austhivenet1',
    storageBucket: 'austhivenet1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRBf_dChhDo5F5sbfiP2ssNquCCp9DEw0',
    appId: '1:132147122480:ios:785013b62af209325278f5',
    messagingSenderId: '132147122480',
    projectId: 'austhivenet1',
    storageBucket: 'austhivenet1.appspot.com',
    iosBundleId: 'com.example.austHivenet1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRBf_dChhDo5F5sbfiP2ssNquCCp9DEw0',
    appId: '1:132147122480:ios:785013b62af209325278f5',
    messagingSenderId: '132147122480',
    projectId: 'austhivenet1',
    storageBucket: 'austhivenet1.appspot.com',
    iosBundleId: 'com.example.austHivenet1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiCKs2FMlestAHMgT-l3YujLJ59xS66oE',
    appId: '1:132147122480:web:d95f7e15368f79335278f5',
    messagingSenderId: '132147122480',
    projectId: 'austhivenet1',
    authDomain: 'austhivenet1.firebaseapp.com',
    storageBucket: 'austhivenet1.appspot.com',
    measurementId: 'G-B5JXS1KD3P',
  );

}